name: CI/CD Pipeline for Web-Counter-App

on:
  push:
    branches:
      - main # Trigger on every push to the main branch
    tags:
      - "v*" # Trigger for tags like 'v1.0', 'v2.1', etc.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set Docker Image Tag with Merge Date
      - name: Set Docker Image Tag
        id: set_tag
        run: |
          DATE_TAG=$(date +'%d-%m-%Y')
          echo "TAG_NAME=${DATE_TAG}" >> $GITHUB_ENV

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and Push Docker Image with Date Tag
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/web-counter-app:${{ env.TAG_NAME }}
          push: true

      # Step 6: Set up Kubectl
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.23.0" # Choose a version compatible with your cluster

      # Step 7: Create Kubeconfig file
      # Step 7: Create Kubeconfig file
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > ~/.kube/config

      # Step 8: Deploy Updated Kubernetes Resources
      - name: Deploy to AKS
        run: |
          # Replace the placeholder IMAGE_TAG with the new date-based tag
          sed -i "s|IMAGE_TAG|${{ env.TAG_NAME }}|g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml

      # Step 9: Wait for Deployment Rollout
      - name: Wait for Deployment Rollout
        run: |
          kubectl rollout status deployment/web-counter -n web-count-app
