name: CI/CD Pipeline for Web-Counter-App

on:
  push:
    tags:
      - "v*" # Trigger only for tags like 'v1.0', 'v2.1', etc.
    branches:
      - main # Optional: trigger on every push to main as well.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Determine the Docker image tag
      - name: Set Docker Image Tag
        id: set_tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF_NAME}"  # Use just the tag name
          else
            TAG_NAME="${GITHUB_REF_NAME}"  # Use the branch name (e.g., "main")
          fi
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image with version tag
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/web-counter-app:${{ env.TAG_NAME }}
          push: true

      # Set up Kubectl
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.31.1" # Choose a version compatible with your cluster

      # Create Kubeconfig file
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > ~/.kube/config

      # Deploy to AKS using the versioned image
      - name: Deploy to AKS
        run: |
          kubectl set image deployment/web-counter web-counter=${{ secrets.DOCKER_USERNAME }}/web-counter-app:${{ env.TAG_NAME }} -n web-count-app
